# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/daniel/Projects/gc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/daniel/Projects/gc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniel/Projects/gc/CMakeFiles /Users/daniel/Projects/gc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daniel/Projects/gc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gc

# Build rule for target.
gc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gc
.PHONY : gc

# fast build rule for target.
gc/fast:
	$(MAKE) -f CMakeFiles/gc.dir/build.make CMakeFiles/gc.dir/build
.PHONY : gc/fast

#=============================================================================
# Target rules for targets named testgc

# Build rule for target.
testgc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testgc
.PHONY : testgc

# fast build rule for target.
testgc/fast:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/build
.PHONY : testgc/fast

src/gc.o: src/gc.c.o
.PHONY : src/gc.o

# target to build an object file
src/gc.c.o:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/gc.c.o
.PHONY : src/gc.c.o

src/gc.i: src/gc.c.i
.PHONY : src/gc.i

# target to preprocess a source file
src/gc.c.i:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/gc.c.i
.PHONY : src/gc.c.i

src/gc.s: src/gc.c.s
.PHONY : src/gc.s

# target to generate assembly for a file
src/gc.c.s:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/gc.c.s
.PHONY : src/gc.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/gc.dir/build.make CMakeFiles/gc.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/gc.dir/build.make CMakeFiles/gc.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/gc.dir/build.make CMakeFiles/gc.dir/src/main.c.s
.PHONY : src/main.c.s

src/value.o: src/value.c.o
.PHONY : src/value.o

# target to build an object file
src/value.c.o:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/value.c.o
.PHONY : src/value.c.o

src/value.i: src/value.c.i
.PHONY : src/value.i

# target to preprocess a source file
src/value.c.i:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/value.c.i
.PHONY : src/value.c.i

src/value.s: src/value.c.s
.PHONY : src/value.s

# target to generate assembly for a file
src/value.c.s:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/value.c.s
.PHONY : src/value.c.s

src/vm.o: src/vm.c.o
.PHONY : src/vm.o

# target to build an object file
src/vm.c.o:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/vm.c.o
.PHONY : src/vm.c.o

src/vm.i: src/vm.c.i
.PHONY : src/vm.i

# target to preprocess a source file
src/vm.c.i:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/vm.c.i
.PHONY : src/vm.c.i

src/vm.s: src/vm.c.s
.PHONY : src/vm.s

# target to generate assembly for a file
src/vm.c.s:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/src/vm.c.s
.PHONY : src/vm.c.s

test/gc.o: test/gc.c.o
.PHONY : test/gc.o

# target to build an object file
test/gc.c.o:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/test/gc.c.o
.PHONY : test/gc.c.o

test/gc.i: test/gc.c.i
.PHONY : test/gc.i

# target to preprocess a source file
test/gc.c.i:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/test/gc.c.i
.PHONY : test/gc.c.i

test/gc.s: test/gc.c.s
.PHONY : test/gc.s

# target to generate assembly for a file
test/gc.c.s:
	$(MAKE) -f CMakeFiles/testgc.dir/build.make CMakeFiles/testgc.dir/test/gc.c.s
.PHONY : test/gc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gc"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... testgc"
	@echo "... src/gc.o"
	@echo "... src/gc.i"
	@echo "... src/gc.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/value.o"
	@echo "... src/value.i"
	@echo "... src/value.s"
	@echo "... src/vm.o"
	@echo "... src/vm.i"
	@echo "... src/vm.s"
	@echo "... test/gc.o"
	@echo "... test/gc.i"
	@echo "... test/gc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

